'use strict';

/**
 * Application materials.
 *
 * Until now Slate stored no documents at all: server/candidates.js records a
 * *reference* to a resume held in the client's approved repository, and refuses
 * to become a way of making a restricted document reachable. Accepting an
 * upload from a member of the public is a genuine change to that model, so
 * everything here is built to be conservative about it.
 *
 * What that means concretely, following OWASP's file-upload guidance:
 *
 *  - The storage key is generated. The name the applicant's computer gave the
 *    file is kept only as a label to show them, is never used as a path, and
 *    cannot escape the directory even if it tries.
 *  - The file type is checked twice: the declared type and extension against
 *    an allowlist, and then the first bytes of the content against the same
 *    answer. A .pdf that is not a PDF is refused.
 *  - Size and count are bounded, per file and per application.
 *  - Nothing is readable by a reviewer until a scanner has cleared it. With no
 *    scanner configured, that means nothing is readable, and the record says
 *    so in plain words rather than quietly showing a download that opens an
 *    unscanned file.
 *  - Downloads are authorized per request against the owning application and
 *    workspace. There is no unguessable-URL-as-security here.
 *
 * Choosing a scanner, and owning the storage, retention, backup and cleanup
 * that go with holding people's resumes, is operations work the plan names and
 * this module does not pretend to have done.
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

// Deliberately narrow to start with. PDF is the format every applicant can
// produce and every reviewer can open, and each addition is a new parser
// pointed at a file a stranger chose. The accommodation route for somebody who
// cannot produce one is the posting's support contact, which is why a posting
// cannot be published without one.
const TYPES = [
  {
    ext: 'pdf',
    mime: 'application/pdf',
    // %PDF-
    magic: [0x25, 0x50, 0x44, 0x46, 0x2d]
  }
];

const MAX_BYTES = 8 * 1024 * 1024;
const MAX_FILES = 6;

// How the scan state reads to each audience. A pending file is not a broken
// file, and an applicant should not think their application failed.
const SCAN_STATES = {
  pending: {
    staff: 'Waiting on a virus scan. It cannot be opened until the scan completes.',
    applicant: 'Received. It is being checked before the search team can open it.'
  },
  clean: {
    staff: 'Scanned and available.',
    applicant: 'Received.'
  },
  infected: {
    staff: 'Quarantined: the scanner reported this file as unsafe. It cannot be opened.',
    applicant: 'This file could not be accepted. Please send a replacement, or contact the search team.'
  },
  unavailable: {
    staff: 'No scanner is configured on this deployment, so this file has not been checked and cannot be opened.',
    applicant: 'Received. It is being checked before the search team can open it.'
  }
};

function scannerName() {
  const chosen = String(process.env.SLATE_FILE_SCANNER || 'none').trim().toLowerCase();
  return ['none', 'accept-all'].includes(chosen) ? chosen : 'none';
}

/**
 * What the deployment can honestly say about scanning.
 *
 * `accept-all` is a pilot setting and names itself as one: it marks files
 * openable without scanning them, and the record keeps `scanned: false` so
 * nobody later reads a clean state as evidence that a scan happened.
 */
function scannerStatus() {
  const scanner = scannerName();
  return {
    scanner,
    scans: scanner !== 'none',
    note: scanner === 'none'
      ? 'No file scanner is configured. Uploaded materials are stored and are not available to reviewers.'
      : 'Files are marked available without being scanned (SLATE_FILE_SCANNER=accept-all). This is a pilot setting, not a scan.'
  };
}

function uploadsEnabled() {
  return String(process.env.SLATE_APPLICATION_UPLOADS || '').trim().toLowerCase() === 'on';
}

/**
 * Where the bytes live.
 *
 * Under the data directory, beside the store, so the existing snapshot and
 * mirror in server/recovery.js already cover them and a restore brings back
 * the documents along with the records that reference them.
 */
function root(dataDir) {
  return path.join(dataDir, 'application-files');
}

function directoryFor(dataDir, applicationId) {
  // The application id is generated by this application, not submitted, but
  // it is on a filesystem path so it is checked anyway.
  if (!/^[A-Za-z0-9_-]{1,64}$/.test(String(applicationId))) throw new Error('Bad application id.');
  return path.join(root(dataDir), String(applicationId));
}

function pathFor(dataDir, applicationId, key) {
  if (!/^[a-f0-9]{32}\.[a-z0-9]{1,8}$/.test(String(key))) throw new Error('Bad file key.');
  return path.join(directoryFor(dataDir, applicationId), String(key));
}

/* ------------------------------------------------------------------ *
 * Validation
 * ------------------------------------------------------------------ */

function typeFor(filename, declared) {
  const ext = String(path.extname(String(filename || ''))).replace('.', '').toLowerCase();
  const byExt = TYPES.find(t => t.ext === ext);
  const byMime = TYPES.find(t => t.mime === String(declared || '').toLowerCase().split(';')[0].trim());
  // Both have to agree. A PDF mime type on a .exe, or the reverse, is a
  // deliberate attempt rather than a mistake worth being helpful about.
  if (!byExt || !byMime || byExt !== byMime) return null;
  return byExt.ext;
}

function looksLike(type, buffer) {
  if (!type?.magic) return true;
  if (buffer.length < type.magic.length) return false;
  return type.magic.every((byte, index) => buffer[index] === byte);
}

/**
 * The label shown beside the file.
 *
 * The applicant's own filename, with everything that could make it a path or a
 * markup fragment taken out. It is presentation only: nothing reads it back as
 * a location.
 */
function safeLabel(filename) {
  return String(filename || 'document')
    .replace(/[\\/]/g, ' ')
    .replace(/[^\w .()\-]/g, '')
    .replace(/\s+/g, ' ')
    .trim()
    .slice(0, 120) || 'document';
}

function validate({ filename, contentType, data, existing = 0 }) {
  if (!uploadsEnabled()) {
    return { error: 'This deployment is not accepting file uploads. Follow the application instructions on the posting.' };
  }
  if (existing >= MAX_FILES) return { error: 'You can attach at most ' + MAX_FILES + ' files to an application.' };
  if (typeof data !== 'string' || !data) return { error: 'Choose a file to attach.' };

  const type = TYPES.find(t => t.ext === typeFor(filename, contentType));
  if (!type) {
    return { error: 'Attach a PDF. If you cannot produce one, use the support contact on this posting and the search team will arrange another way.' };
  }

  let buffer;
  try { buffer = Buffer.from(data, 'base64'); }
  catch { return { error: 'That file could not be read. Try attaching it again.' }; }
  if (!buffer.length) return { error: 'That file is empty.' };
  if (buffer.length > MAX_BYTES) {
    return { error: 'Files have to be under ' + Math.round(MAX_BYTES / (1024 * 1024)) + ' MB.' };
  }
  if (!looksLike(type, buffer)) {
    return { error: 'That file is not a PDF, whatever its name says. Attach the PDF itself.' };
  }
  return { type, buffer };
}

/* ------------------------------------------------------------------ *
 * Storage
 * ------------------------------------------------------------------ */

/**
 * Write the bytes and return the metadata record.
 *
 * The record goes on the application; the bytes never do. Storing a resume
 * inside the JSON store would put it in every snapshot, every export path, and
 * every in-memory clone the integrity check makes on save.
 */
function store(dataDir, applicationId, { type, buffer, filename, materialKey }) {
  const key = crypto.randomBytes(16).toString('hex') + '.' + type.ext;
  const dir = directoryFor(dataDir, applicationId);
  fs.mkdirSync(dir, { recursive: true, mode: 0o700 });
  fs.writeFileSync(path.join(dir, key), buffer, { mode: 0o600 });

  const scanner = scannerName();
  return {
    id: 'af-' + crypto.randomBytes(6).toString('hex'),
    key,
    materialKey: String(materialKey || '').slice(0, 40) || null,
    label: safeLabel(filename),
    contentType: type.mime,
    bytes: buffer.length,
    sha256: crypto.createHash('sha256').update(buffer).digest('hex'),
    uploadedAt: new Date().toISOString(),
    scan: {
      // Honest from the first moment. `accept-all` says it did not scan.
      state: scanner === 'accept-all' ? 'clean' : 'unavailable',
      scanner,
      scanned: false,
      at: new Date().toISOString()
    }
  };
}

/** May a reviewer open this file? Only a cleared scan says yes. */
function readable(file) {
  return file?.scan?.state === 'clean';
}

function read(dataDir, applicationId, file) {
  return fs.readFileSync(pathFor(dataDir, applicationId, file.key));
}

/** Remove the bytes for one application. Used when a draft expires. */
function removeAll(dataDir, applicationId) {
  const dir = directoryFor(dataDir, applicationId);
  try {
    fs.rmSync(dir, { recursive: true, force: true });
    return true;
  } catch { return false; }
}

function remove(dataDir, applicationId, file) {
  try { fs.unlinkSync(pathFor(dataDir, applicationId, file.key)); return true; }
  catch { return false; }
}

/**
 * How a file reads to each side.
 *
 * Two projections rather than one with a flag, so the applicant's view cannot
 * accidentally inherit a staff field. Neither carries the storage key: a
 * download is asked for by file id and authorized per request.
 */
function staffView(file) {
  return {
    id: file.id,
    label: file.label,
    materialKey: file.materialKey,
    contentType: file.contentType,
    bytes: file.bytes,
    uploadedAt: file.uploadedAt,
    scanState: file.scan.state,
    scanned: Boolean(file.scan.scanned),
    scanner: file.scan.scanner,
    available: readable(file),
    note: SCAN_STATES[file.scan.state]?.staff || ''
  };
}

function applicantView(file) {
  return {
    id: file.id,
    label: file.label,
    materialKey: file.materialKey,
    bytes: file.bytes,
    uploadedAt: file.uploadedAt,
    // An applicant is told their file arrived and is being checked. They are
    // not shown the scanner's name or the deployment's configuration.
    state: file.scan.state === 'infected' ? 'rejected' : 'received',
    note: SCAN_STATES[file.scan.state]?.applicant || ''
  };
}

module.exports = {
  TYPES, MAX_BYTES, MAX_FILES, SCAN_STATES,
  scannerName, scannerStatus, uploadsEnabled,
  root, directoryFor, pathFor, typeFor, safeLabel,
  validate, store, read, readable, remove, removeAll,
  staffView, applicantView
};
