'use strict';

// Downloads the three web fonts into public/fonts/ and writes the @font-face
// rules that replace the Google Fonts <link>. Run it by hand when a family or
// weight changes; the output is committed as a static asset, not fetched at
// build or request time.
//
// Two reasons this is vendored rather than linked:
//  1. Candidate questionnaire pages are opened by members of the public
//     holding a bearer link. Linking fonts.googleapis.com discloses each
//     candidate's IP address and the page they opened to a third party.
//  2. Self-hosting lets the Content-Security-Policy stay 'self' for both
//     style-src and font-src, with no third-party origin allow-listed.
//
// All three families are licensed under the SIL Open Font License 1.1, which
// permits redistribution. See public/fonts/LICENSE.txt.

const fs = require('fs');
const path = require('path');
const https = require('https');
const crypto = require('crypto');

const OUT = path.resolve(__dirname, '..', 'public', 'fonts');
const CSS_URL = 'https://fonts.googleapis.com/css2'
  + '?family=Newsreader:ital,opsz,wght@0,6..72,400;0,6..72,500;0,6..72,600;1,6..72,400'
  + '&family=Public+Sans:wght@400;500;600;700'
  + '&family=IBM+Plex+Mono:wght@400;500'
  + '&display=swap';

// Google serves woff2 only to user agents it recognises as supporting it.
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
  + '(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36';

// Latin coverage is enough for US local-government searches. Other subsets are
// dropped so the vendored payload stays small.
const KEEP_SUBSETS = new Set(['latin', 'latin-ext']);

function fetch(url, binary) {
  return new Promise((resolve, reject) => {
    https.get(url, { headers: { 'User-Agent': UA } }, response => {
      if (response.statusCode >= 300 && response.statusCode < 400 && response.headers.location) {
        return fetch(response.headers.location, binary).then(resolve, reject);
      }
      if (response.statusCode !== 200) return reject(new Error(url + ' -> HTTP ' + response.statusCode));
      const chunks = [];
      response.on('data', c => chunks.push(c));
      response.on('end', () => resolve(binary ? Buffer.concat(chunks) : Buffer.concat(chunks).toString('utf8')));
    }).on('error', reject);
  });
}

(async () => {
  const css = await fetch(CSS_URL, false);
  fs.mkdirSync(OUT, { recursive: true });

  // Google's stylesheet emits one @font-face per family/style/weight/subset,
  // each preceded by a /* subset */ comment.
  const blocks = css.split('@font-face').slice(1);
  const rules = [];
  let subset = '';
  let downloaded = 0;
  const seen = new Set();

  for (const [index, raw] of blocks.entries()) {
    const before = css.split('@font-face')[index];
    const marker = before.match(/\/\*\s*([a-z0-9-]+)\s*\*\/\s*$/i);
    if (marker) subset = marker[1];
    if (!KEEP_SUBSETS.has(subset)) continue;

    const family = raw.match(/font-family:\s*'([^']+)'/)?.[1];
    const style = raw.match(/font-style:\s*([^;]+);/)?.[1].trim() || 'normal';
    const weight = raw.match(/font-weight:\s*([^;]+);/)?.[1].trim() || '400';
    const range = raw.match(/unicode-range:\s*([^;]+);/)?.[1].trim();
    const url = raw.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1];
    if (!family || !url) continue;

    // Newsreader and Public Sans are variable fonts: Google returns the same
    // file for every weight in the range. Store one copy per distinct payload
    // and let several @font-face rules point at it. The content hash in the
    // name also makes the file safely cacheable forever.
    const bytes = await fetch(url, true);
    const hash = crypto.createHash('sha256').update(bytes).digest('hex').slice(0, 8);
    const file = [
      family.toLowerCase().replace(/\s+/g, '-'),
      style === 'italic' ? 'italic' : 'normal',
      subset,
      hash
    ].join('-') + '.woff2';

    if (!seen.has(file)) {
      fs.writeFileSync(path.join(OUT, file), bytes);
      seen.add(file);
      downloaded += 1;
    }

    rules.push([
      '@font-face {',
      "  font-family: '" + family + "';",
      '  font-style: ' + style + ';',
      '  font-weight: ' + weight + ';',
      '  font-display: swap;',
      "  src: url('/fonts/" + file + "') format('woff2');",
      range ? '  unicode-range: ' + range + ';' : null,
      '}'
    ].filter(Boolean).join('\n'));
  }

  if (!rules.length) throw new Error('No @font-face rules were produced; the upstream CSS format may have changed.');

  fs.writeFileSync(path.join(OUT, 'fonts.css'),
    '/* Generated by scripts/vendor-fonts.js. Do not edit by hand.\n'
    + '   Newsreader, Public Sans and IBM Plex Mono, SIL Open Font License 1.1.\n'
    + '   Regenerate with: node scripts/vendor-fonts.js */\n\n'
    + rules.join('\n\n') + '\n');

  console.log('Wrote ' + downloaded + ' font files and ' + rules.length + ' @font-face rules to public/fonts/');
})().catch(error => { console.error(error.message); process.exitCode = 1; });
